version: "3"
services:
  samba:
    build: .
    environment:
      - USER=user;password
      - SHARE=share;/share;yes;no;yes
      - SHARE1=IT;/IT;yes;no;yes
      - SHARE2=accounting;/accounting;yes;no;yes
      - SHARE3=bussiness;/bussiness;yes;no;yes
      - SHARE4=close;/bussiness;yes;no;no
      - FLAG=test
    ports:
      - 139:139
      - 445:445