apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-data
data:
  database.sql: |
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";


    CREATE TABLE `users_info` (
      `id` int UNSIGNED NOT NULL,
      `login` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
      `password` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
      `vocation` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;


    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (1, 'admin', 'hguerhg@!r32hf2buJHfe', 'Devops');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (2, 'moderator', 'oijrgoih34g234', 'Backend programmer');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (3, 'Sam', 'mirthmjiotjr', 'Frontend programmer');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (4, 'John', 'hn9u5aHGU4G', 'Designer');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (5, 'Anna', 'k9isughus443tyh', 'Trainee');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (6, 'Kyle', 'cu3hg9ijspcj', 'Data analyst');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (7, 'Lina', '{{ .Flag }}', 'AI');

    ALTER TABLE `users_info`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `id` (`id`);

    ALTER TABLE `users_info`
      MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-sqlmap-env
data:
  MARIADB_DATABASE: "users"
  MARIADB_ROOT_PASSWORD: "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-spawn-env
data:
  DB_USER: "root"
  DB_PASS: "password"
  DB_HOST: "admin-spawn-{{ .ClientName }}"

---
apiVersion: v1
kind: Pod
metadata:
  name: admin-spawn
  labels:
    app: admin-spawn-{{ .ClientName }}
    client: "{{ .ClientName }}"
spec:
  containers:
    - name: admin-spawn
      image: cotsom/web-sqlmap:latest
      ports:
        - containerPort: 5000
      resources:
        limits:
          memory: 30Mi
          cpu: "0.2"
        requests:
          memory: 30Mi
          cpu: "0.2"
      envFrom:
        - configMapRef:
            name: admin-spawn-env-{{ .ClientName }}
    - name: mariadb
      image: mariadb:10.8.2
      ports:
        - containerPort: 3306
      resources:
        limits:
          memory: 160Mi
          cpu: "0.2"
        requests:
          memory: 160Mi
          cpu: "0.2"
      envFrom:
        - configMapRef:
            name: db-sqlmap-env-{{ .ClientName }}
      volumeMounts:
        - name: data
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: data
      configMap:
        name: sql-data-{{ .ClientName }}
