apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-researcher-flag
data:
  flag.txt: |
    {{ .Flag }}

---
apiVersion: v1
kind: Pod
metadata:
  name: domain-researcher
  labels:
    app: domain-researcher-{{ .ClientName }}
    client: "{{ .ClientName }}"
spec:
  containers:
    - name: domain-researcher
      image: cotsom/web-burp:latest
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: domain-researcher-flag
          mountPath: /home/user/
      resources:
          limits:
            memory: 10Mi
            cpu: "0.1"
          requests:
            memory: 10Mi
            cpu: "0.1"
  volumes:
    - name: domain-researcher-flag
      configMap:
        name: domain-researcher-flag-{{ .ClientName }}