apiVersion: v1
kind: ConfigMap
metadata:
  name: privesc-env
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
  SUDO_ACCESS: "true" #optional
  PASSWORD_ACCESS: "true" #optional
  USER_PASSWORD: "prohacker" #optional
  USER_NAME: "user" #optional

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: privesc-flag
data:
  flag.txt: |
    test12345

---
apiVersion: v1
kind: Pod
metadata:
  name: privesc-lab
  labels:
    app: privesc-lab-pod
spec:
  containers:
    - name: ssh
      image: cotsom/privesc:latest
      ports:
        - containerPort: 2222
      envFrom:
        - configMapRef:
            name: privesc-env
      volumeMounts:
        - name: privesc-flag
          mountPath: /root/
      resources:
          limits:
            memory: 20Mi
            cpu: "0.1"
          requests:
            memory: 20Mi
            cpu: "0.1"
  volumes:
    - name: privesc-flag
      configMap:
        name: privesc-flag
