apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-env
data:
  USER: "user;secret"
  SHARE: "bussiness;/bussiness;yes;no;yes"
  SHARE1: "IT;/IT;yes;no;yes"
  SHARE2: "accounting;/accounting;yes;no;yes"
  SHARE3: "stuff;/stuff;yes;no;yes"
  SHARE4: "share;/share;yes;no;no"
  SHARE5: "documents;/documents;yes;no;yes"
  FLAG: {{ .Flag }}

---
apiVersion: v1
kind: Pod
metadata:
  name: samba
  labels:
    app: samba-{{ .ClientName }}
    client: "{{ .ClientName }}"
spec:
  containers:
    - name: samba
      image: cotsom/samba:latest
      ports:
        - containerPort: 139
        - containerPort: 445
      envFrom:
        - configMapRef:
            name: samba-env-{{ .ClientName }}
      resources:
          limits:
            memory: 10Mi
            cpu: "0.1"
          requests:
            memory: 10Mi
            cpu: "0.1"
