apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-shell-env
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
  SUDO_ACCESS: "true" #optional
  PASSWORD_ACCESS: "true" #optional
  USER_PASSWORD: "powercat" #optional
  USER_NAME: "user" #optional

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-shell-flag
data:
  flag.txt: |
    {{ .Flag }}

---
apiVersion: v1
kind: Pod
metadata:
  name: secure-shell
  labels:
    app: secure-shell-{{ .ClientName }}
    client: "{{ .ClientName }}"
spec:
  containers:
    - name: secure-shell
      image: lscr.io/linuxserver/openssh-server:latest
      ports:
        - containerPort: 2222
      envFrom:
        - configMapRef:
            name: secure-shell-env-{{ .ClientName }}
      volumeMounts:
        - name: secure-shell-flag
          mountPath: /home/user/
      resources:
          limits:
            memory: 10Mi
            cpu: "0.1"
          requests:
            memory: 10Mi
            cpu: "0.1"
  volumes:
    - name: secure-shell-flag
      configMap:
        name: secure-shell-flag-{{ .ClientName }}
