apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-env
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"
  SUDO_ACCESS: "true" #optional
  PASSWORD_ACCESS: "true" #optional
  USER_PASSWORD: "password" #optional
  USER_NAME: "user" #optional

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-flag
data:
  flag.txt: |
    test123

---
apiVersion: v1
kind: Pod
metadata:
  name: ssh-lab
  labels:
    app: ssh-lab-pod
spec:
  containers:
    - name: ssh
      image: lscr.io/linuxserver/openssh-server:latest
      ports:
        - containerPort: 2222
      envFrom:
        - configMapRef:
            name: ssh-env
      volumeMounts:
        - name: ssh-flag
          mountPath: /home/user/
      resources:
          limits:
            memory: 10Mi
            cpu: "0.1"
          requests:
            memory: 10Mi
            cpu: "0.1"
  volumes:
    - name: ssh-flag
      configMap:
        name: ssh-flag
