apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-data
data:
  docker-entrypoint-initdb.d: |
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";


    CREATE TABLE `users_info` (
      `id` int UNSIGNED NOT NULL,
      `login` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
      `password` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
      `vocation` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;


    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (1, 'admin', 'hguerhg@!r32hf2buJHfe', 'Devops');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (2, 'moderator', 'oijrgoih34g234', 'Backend programmer');
    INSERT INTO `users_info` (`id`, `login`, `password`, `vocation`) VALUES
    (3, 'Sam', 'oijh348ufh34f234', 'Frontend programmer');

    ALTER TABLE `users_info`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `id` (`id`);

    ALTER TABLE `users_info`
      MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-sqlmap-env
data:
  MYSQL_DATABASE: "users"
  MYSQL_ROOT_PASSWORD: "password"

---
apiVersion: v1
kind: Pod
metadata:
  name: web-sqlmap-lab
  labels:
    app: web-sqlmap-pod
spec:
  containers:
    - name: web-sqlmap
      image: cotsom/web-sqlmap:latest
      ports:
        - containerPort: 5000
      resources:
        limits:
          memory: 10Mi
          cpu: "0.1"
        requests:
          memory: 10Mi
          cpu: "0.1"
    - name: mariadb
      image: mariadb
      resources:
        limits:
          memory: 10Mi
          cpu: "0.1"
        requests:
          memory: 10Mi
          cpu: "0.1"
      envFrom:
        - configMapRef:
            name: web-sqlmap-env
      volumeMounts:
        - name: data
          mountPath: /docker-entrypoint-initdb.d/
  volumes:
    - name: data
      configMap:
        name: sql-data
