apiVersion: v1
kind: ConfigMap
metadata:
  name: where-is-exit-flag
data:
  flag.txt: |
    test123

---
apiVersion: v1
kind: Pod
metadata:
  name: where-is-exit
  labels:
    app: where-is-exit-{{ .ClientName }}
    client: "{{ .ClientName }}"
spec:
  containers:
    - name: where-is-exit
      image: cotsom/privesc-vim:latest
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: where-is-exit-flag
          mountPath: /root/flag.txt
          subPath: flag.txt
      resources:
          limits:
            memory: 10Mi
            cpu: "0.1"
          requests:
            memory: 10Mi
            cpu: "0.1"
  volumes:
    - name: where-is-exit-flag
      configMap:
        name: where-is-exit-flag-{{ .ClientName }}
        defaultMode: 0600
