version: "3"
services:
  openssh-server:
    build: 
      context: .
    image: cotsom/privesc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=prohacker #optional
      - USER_NAME=user #optional
    ports:
      - 2222:2222
    restart: always