version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=password
      - PYTHONUNBUFFERED=1
    volumes:
     - ./sql:/docker-entrypoint-initdb.d:ro

    
